//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR2_Parfenchyk.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderUser
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int UserID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
}
